USE [FIX];
GO

CREATE LOGIN [trading] WITH PASSWORD=N'Pictet123', CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO

CREATE USER [trading] FOR LOGIN [trading];
GO

CREATE SCHEMA [FIX.4.2] AUTHORIZATION [trading];
GO

ALTER ROLE [db_datareader] ADD MEMBER [trading];
GO